### ISSUE TITLE
Closed issue and general functionality testing Arch Staging

### ISSUE THREAD

**Issue by davidschober** [nulib/arch#110]
@cpd3149 and @nulib/repodev : 

We would like a sanity check on the closed issues, and general functionality before moving to production.

## General Functionality:

- [x] Login
- [x] logout
- [x] search shows records
- [x] deposit a work (video is still a bit buggy, pdf, word, excel)
- [x] thumbnail generated after new work is deposited (note this may take some time)
- [x] Display generally good/ issues created. 

### Frontend/ User

- [x] Add Chris Diaz as admin on arch/ help wanted question #57 
- [x] can't login to arch-s #55 
- [x] Create Test Works for Staging #51 
- [x] Change "Create Work" label to "Upload copy ux #50 
- [x] Add Bootstrap JS tooltip to metadata create/edit form  ux #49
- [x] Facets for Limiting Search Results is Missing bug ux #46
- [x] Contact Form Doesn't Deliver Messages bug #42 
- [x] Adjust width constraints to main content wrapper #41 
- [x] Change Arch Header Text to LIBRARIES | Arch change ux #39 
- [x] Add "Download" Action to file records enhancement ux #36 
- [x] Batch Deleting private files reappear as deposits and attachments bug  #33 
- [x] Image for "Preserve and Share your work" box enhancement #26 

### Systems

- [ ] Devlopers have lost ssh access to nufiaweb-s/vagrant devops #90 
- [ ] update sufia to latest 7.x enhancement production staging #48 
- [ ] Fedora down on staging devops #89 
- [ ] Vagrant user needs access to nufia-s #86
- [ ] Investigate Derivatives Path Configuration discussion quality assuranc #74 
- [ ] Upgrade fits version on staging (nufiaweb-s) devops #69 
- [ ] Problem with LibreOffice on nufiaweb-s devops  #65 
- [ ] Ensure puppet code on github is current devops #64
- [ ] ssh access for ksd927 on nufiarepo-s devops #63
