### ISSUE TITLE
Hyrax Arch UI Updates

### ISSUE THREAD

**Issue by adamjarling** [nulib/arch#229]
### Description 
Master issue containing sub-tasks/issues for updating NU Arch Hyrax UI / CSS.

- [x] #228 Update Sass architecture to 7-1 pattern
- [x] #158 Update search styling
- [x] #116 CSS/Browser issues on Thumbnail display on My Works page
- [x] #226 Arch Works form "Add Another" gets truncated in Safari
- [x] #227 Filter works by facet on My Works page display issue
- [x] #230 Button icons missing
- [x] #231 Form Input active/focus state
- [x] #190 NU tabs style
- [x] #232 Secondary button text color
- [x] #233 Update alert colors
- [x] #237 Update homepage
