### ISSUE TITLE
Large File Box Upload

### ISSUE THREAD

**Issue by kdid** [nulib/arch#320]
Just consolidating current issues/limitations in one place

- [ ] Move fedora data to Isilon (https://github.com/nulib/devops/issues/140)
- [x] Box limit on file uploads to 15G per file: http://www.it.northwestern.edu/file-sharing/overview.html
- [x] Disk space nufiaweb-s
- [x] Memory nufiaweb-s
- [x] BrowseEverything not streaming from Box
- [x] Disk space on Fedora for large binaries (nufiarepo-s) (#346) 
- [x] .zip extention not preserved (user would have to download and rename the file to open, noted by Chris D. for other file types as well in https://github.com/nulib/institutional-repository/issues/318)
- [ ] Hyrax jobs not recognizing error in ImportUrlJob (Issue #325). End result is html error page from box ends up in Fedora (?). Sidekiq log here: https://gist.github.com/kdid/6e30210fd1b78454764b4837f9ea7fee . Example (click download): https://nufiaweb-s.library.northwestern.edu/concern/parent/mk61rh020/file_sets/8c97kq430
- [x] Fits characterizes the .raw files as html . When the user clicks 'Download' the file attempts to open in the browser (crashing some browsers, Safari for me). The file can be downloaded but the user has to right/control click and 'Save As' (Issue #77)
- [x] Fedora (nufiarepo-s) can't find old binaries pre-Isilon data directory move: https://github.com/nulib/institutional-repository/issues/326
- [x] "Box Account Bug" https://github.com/nulib/institutional-repository/issues/310
- [ ] Space issues in /var (Issue #330)
  - [ ] Move uploads to Isilon (Issue #334)
  - [ ] Move derivatives to Isilon (Issue #335)
- [ ] Reminder to configure production with increased resources before deploy.

cc @davidschober
