### ISSUE TITLE
Move Arch to AWS

### ISSUE THREAD

**Issue by davidschober** [nulib/arch#418]
# ARCH

## Description

As part of our goal to move repository services to more resilient and flexible infrastructure, we will move ARCH to AWS. Arch is currently hosted on a single instance in NU Cloud and regularly has issues with multi-file uploads, etc. As part of this move, we would also like to ensure large (>500 meg) files with many numbers > 100 can be uploaded to Arch. We believe having an s3 bucket for use when there are many large files will solve this problem. 

## Key Goals

**ARCH:**

- is hosted on AWS and provisioned with cloud front 
- has workers for background jobs 
- data is backed up to Isilon (similar to Avalon) (open for discussion)
- is monitored using CloudWatch
- will be moved as-is (1.0 with customizations)
- is using the same core infrastructure as Avalon and Donut (SOLR, FEDORA)
- Arch is set to scale
- Dockerizing is out of SCOPE for this cycle

## Key use cases

- [key use cases write up](https://northwestern.app.box.com/notes/279423533567?s=mx33l8dnfn4rthl6ec0gffo4etd2lzhb)

## Done looks like

- [x] Copy application infrastructure template for Arch (from donut) and setup with Arch repos for deployment (Devops w/ repodev support) ( parent of #429 )
- [x] Create S3 Dropbox bucket for Arch, create credentials for Chris/ Digital Scholarship (Devops/Repodev) /  put in template parent of #385 
- [x] Configure travis and code pipeline for automatic deployments parent of #428
- [x] document and implement backup strategy (content, metadata, database, solr) parent of #427
- [x] Deploy arch to staging (Repodev) parent of #424
- [x] Migrate Arch Data to Staging (Repodev) parent of #425
- [x] Test arch on staging (Dig Scholarship) parent of #426
- [x] Add cloud watch and wire to ops genie (DEVOPS) parent of #423
- [x] **Increase upload from 500 to 2 gigs (if needed) -- We may have found a fix (Repodev)**  parent of #337 
~- [ ] Add box support with caveats (e.g. not for massive uploads, s3 dropbox should be used)  (OUT OF SCOPE too much custom work. We've been here before. )~
- [ ] Update docs on use of mediated deposit (s3) (Dig Scholarship) parent of #422
- [x] Develop communication plan on cutover time. We will need a window. parent of #421
- [x] increase max filesets on works to 200 parent of #337
