### ISSUE TITLE
Write Script to Handle Binary Import for AWS Migration

### ISSUE THREAD

**Issue by carrickr** [nulib/arch#449]
To get sample data for a script:

1. Download the import export tool jar from: https://github.com/fcrepo4-labs/fcrepo-import-export/releases
1. Run it against a Fedora endpoint, ex: `java -jar fcrepo-import-export-0.2.0.jar --mode export --resource http://fcrepo.repo.vpc.rdc-staging.library.northwestern.edu/rest/avr --dir /tmp/avr --binaries`
1. Open the directory via atom and search for `hasModel` to avoid getting a Hydra access control/etc

Our script needs to walk the structure on disk looking for everything with `hasModel`, for everything with has model it needs to:
- [x] upload the binary to s3 and rename it from `foo.binary` to `foo.proper_extension` using the extension from `ebucore:filename` in the `ttl` file and post with digest from `premis:hasMessageDigest` to verify fixity
- [x] edit the ttl file so that `ebucore:locator` and `ebucore:filename` point to the s3 uri
- [x] remove `ebucore:hasMimeType` from the `ttl`
- [ ] write an audit tool

# TODOs:
- [x] determine if we can drop `fedora:hasFixityService` from the ttl
- [x] determine if versions are necessary and how to handle them

Then test this using the import tool set not to use binaries
