### ISSUE TITLE
retest after 7.2 update

### ISSUE THREAD

**Issue by davidschober** [nulib/arch#54]
@cpd3149 Can you run through this list and verify whether or not we got some "freebies" with the upgrade. 

- [ ] Facets for Limiting Search Results is Missing bug ready ux #46 
- [ ] Contact Form Doesn't Deliver Messages bug ready #42 
- [x] Adjust width constraints to main content wrapper high priority ready #41 
- [ ] Resize top bar CSS dimensions to 1583 x 60 enhancement ready ux #40 
- [ ] Batch Deleting private files reappear as deposits and attachments bug high priority ready #33 
- [ ] Batch Create results in duplicate files bug high priority ready #32 
- [x] nufiaweb-s intermittent Internal Server (500) Errors devops ready #27 

Add comments to the issues themselves, not here. This will act as just a checkbox.
