### ISSUE TITLE
.7 arch production punchlist

### ISSUE THREAD

**Issue by davidschober** [nulib/arch#558]
## Description

We would like to move Arch to Hyrax 2.0 in production. There are 7 open "high priority" issues  and around 6 low priority issues. After completing the high priority issues we can move to production. The low priority ones are kept as part of this issue because they may naturally inherit from some of the high priority issues.

## High Priority

- [x] Display top-nav on all dashboard views (parent of #553) 
- [x] User Collections are Missing Metadata on Public View (parent of #550)
- [x] LDAP Inconsistencies with Names, Email, and NetIDs bug (parent of #547)
- [x] Disable i18n change high priority hyrax 2.0 upgrade ui (parent of #546)
- [x] .raw files are characterized as .html, creating unexpected download problems (parent of #525)
- [x] Cannot search within a collection (parent of #264)
- [x] Private visibility help text error (parent of #559)
- [x] Add new work tabs broken (parent of #573)
- [x] can't edit admin page (parent of #587)
- [x] DOI should be external link (parent of #592)
- [x] Update Hyrax to (NU) 2.4.1 (parent of #594)

## Medium Priority
- [x] Review UI Styles, make recommendations parent of #549
- [x] BE should only be visible for admin and up parent of #589
- [x] Can't ingest files via s3/dropbox (parent of #572)
- [x] .zip files unable to ingest via s3 dropbox parent of #527
- [x] Inconsistent file characterization when ingesting multiple files via s3 dropbox parent of #526 
- [x] Email Spam from Contact Form change (parent of #556) 
- [x] "Download All" button missing from Work View (#593)

## Low Priority

- [x] Work Descriptions not wrapped in parent of #552
- [x] Remove Is Part Of from collection parent of #551 
- [x] Remove Workflow State Badge change hyrax 2.0 parent of #548 
- [x] Remove Citations form Work View parent of #545
